### PR TITLE
Fixed Logo

### PR DESCRIPTION
**Pull request by GeorgeButler**
* Fixed Logo
* Allowing up to 10k starting money

### CODE REVIEW

**Comment by GeorgeButler** [comment]
.

**Comment by HeyBanditoz** [comment]
I don't think it's a good idea to change a default value in the config like money. Also, we could also move the logo to something like Imgur or mixtape.moe

**Comment by GeorgeButler** [comment]
@HeyBanditoz I raised the maximum value for the starting money, because I faced some issues where using currency that's valued far under USD bigger numbers were required and it seemed arbitrary to limit it to 1,000. Also I'm fine with reuploading the logo, but the problem is theres no central nutscript content host that I have access to at the moment so the logo's ability to show would depend on those site's server availability.

**Comment by HeyBanditoz** [comment]
Imgur has really good fucking uptime. Mixtape.moe is pretty good, but I've seen it go down once.
As per the default money change, I don't develop for schemas, so I wouldn't know.

**Pull request merged**
