### PR TITLE
Two plugins loading

### PR DESCRIPTION
**Pull request by Heyter**
rewriting

### CODE REVIEW

**Comment by brianhang** [comment]
What is the issue exactly? Is `engine.ActiveGamemode()` returning "nutscript"?

Maybe the Initialize hook is too early to use `engine.ActiveGamemode`. But, it apparently works in the PostGamemodeLoaded hook.

**Comment by brianhang** [comment]
Also, this seems to imply the schema wouldn't load correctly at all.

**Comment by Heyter** [comment]
> Also, this seems to imply the schema wouldn't load correctly at all.

i tested, all loading correctly or u can check it.

**Comment by brianhang** [comment]
I'm talking about before this patch. If it wasn't giving the right gamemode back, then the schema wouldn't have loaded. Did your schema not load before? Or was it just the plugins in the schema?

**Comment by Heyter** [comment]
> I'm talking about before this patch. If it wasn't giving the right gamemode back, then the schema wouldn't have loaded. Did your schema not load before? Or was it just the plugins in the schema?

Okay, i close it.

**Pull request closed without merging**
