### PR TITLE
Restrict vendor editing to super administrators.

### PR DESCRIPTION
**Pull request by DefenderVex**
This is to prevent lower authority staff members from editing the vendor when they shouldn't.

### CODE REVIEW

**Comment by rebel1324** [comment]
hmmm, we need to think about this issue.

**Comment by DefenderVex** [comment]
It's an issue sadly i'm finding that's happening more and more. Since the common permission solutions such as ULX assign at last admin status to most ranks it allows a great deal of people to edit this. I think this and at least logging to be introduced to at least mitigate the issue.

**Comment by Rubberbandits** [comment]
i doubt the proper way to solve this is by forcing a framework change.

**Comment by DefenderVex** [comment]
I'm not trying to force a change. Considering the fact that the Garry's Mod admin tag is more regularly assigned to ranks more than the SuperAdmin tag you can run into issues where people who shouldn't necessarily be editing vendors doing just that.

**Comment by rebel1324** [comment]
Maybe we can add some option like Only Allow Superadmin to add vendors or something mate

**Pull request closed without merging**
